[package]
name = "redirectionio-cloudflare-worker"
version = "0.1.0"
authors = []
edition = "2018"
publish = false

[profile.release]
debug = 1

[dependencies]
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }
log = "0.4.14"
redirectionio = "=2.5.2"
# Uncomment the following line to debug
#redirectionio = { path = "../../agent/libredirectionio/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.70"
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = "0.2.78"
wasm-logger = "0.2.0"

[lib]
crate-type = ["cdylib", "rlib"]
